[tool.poetry]
name = "eoftoolkit"
version = "0.0.1"
description = ""
authors = ["Mohammad Kordgholiabad <mohammadkord99@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
